DROP TABLE IF EXISTS food CASCADE;

CREATE TABLE food (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  price FLOAT NOT NULL,
  thumbnail_url VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  time INTEGER NOT NULL
);
