DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ready_at TIMESTAMP,
  order_status VARCHAR(255) NOT NULL,
  completed_at TIMESTAMP,
  price DECIMAL(10,2) NOT NULL
);
